name: GoodGuySwag
favicon: null
layout_spectrum: 0.76197
typography_spectrum: 0.5556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1b1d'
    - '#ef1e24'
    - '#fefefe'
    - '#6d6f6e'
    - '#999997'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
